# Generated by Django 5.0.6 on 2024-07-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_health', models.IntegerField(default=100)),
                ('enemy_health', models.IntegerField(default=500)),
                ('user_action', models.CharField(blank=True, max_length=10, null=True)),
                ('enemy_action', models.CharField(blank=True, max_length=10, null=True)),
                ('game_over', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
